language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
  - wget -c https://files.seeedstudio.com/arduino/seeed-arduino-ci.sh

script:
   - chmod +x seeed-arduino-ci.sh
   - cat $PWD/seeed-arduino-ci.sh
   - bash $PWD/seeed-arduino-ci.sh -b "Seeeduino:samd:seeed_wio_terminal" -s BLE_client/BLE_server/BLE_iBeacon/BLE_iBeacon_3Asix/BLE_scan/BLE_uart Seeed-Studio/Seeed_Arduino_FreeRTOS.git Seeed-Studio/Seeed_Arduino_rpcUnified.git Seeed-Studio/Seeed_Arduino_LIS3DHTR.git

notifications:
  email:
    on_success: change
    on_failure: change
